Rematch_Text_LeaderAskRematch::
	.string "Care for a rematch?\n"
	.string "I won't hold back this time!$"

Rematch_Text_LeaderPostRematch::
	.string "Incredible!\n"
	.string "You've grown even stronger…\p"
	.string "Come back anytime.\n"
	.string "I'll have a new team waiting!$"

Rematch_Text_LeaderDeclineRematch::
	.string "Come back whenever you're ready.\n"
	.string "I'll be waiting for a rematch!$"
