#!/usr/bin/env python3
"""Generate src/data/pokemon/experience_tables.h for MAX_LEVEL = 255.

Levels 0..100 reproduce the vanilla Gen 3 tables exactly (verified against the
compiled vanilla values). Levels 101+ continue each growth rate's Gen 3
closed-form formula, emitted as plain u32 literals so no compile-time integer
overflow can occur (Fluctuating's intermediates exceed s32 past ~level 240).

The one exception is Erratic: its final piece (160 - n) * n^3 / 100 is only
defined up to 100 and stays monotonic only through its peak at level 120
(negative past 160), so it follows the closed form through 120 and then grows
linearly by its own 99->100 step per level. Every other rate is the pure
formula all the way to 255.

Totals at 255 (largest: Fluctuating 52,728,772) need 26 bits; the experience
field in PokemonSubstruct0 is 24 low bits + 2 high bits stored in previously
unused padding, composed in Get/SetBoxMonData.

Usage: python3 tools/gen_exp_tables.py          # rewrites the header
       python3 tools/gen_exp_tables.py --check  # verify only, write nothing
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src/data/pokemon/experience_tables.h"
MAX_LEVEL = 255
EXP_BITS = 26  # experience:24 low bits + experienceHi:2 in PokemonSubstruct0


# Gen 3 formulas with C integer semantics (all divisions truncate; every
# operand below is non-negative on the levels where the formula is used).
def medium_fast(n): return n * n * n
def fast(n):        return 4 * n * n * n // 5
def slow(n):        return 5 * n * n * n // 4
def medium_slow(n): return 6 * n * n * n // 5 - 15 * n * n + 100 * n - 140

def erratic_vanilla(n):
    if n <= 50:  return (100 - n) * n * n * n // 50
    if n <= 68:  return (150 - n) * n * n * n // 100
    if n <= 98:  return ((1911 - 10 * n) // 3) * n * n * n // 500
    return (160 - n) * n * n * n // 100

def fluctuating(n):
    if n <= 15:  return ((n + 1) // 3 + 24) * n * n * n // 50
    if n <= 36:  return (n + 14) * n * n * n // 50
    return (n // 2 + 32) * n * n * n // 50

ERRATIC_PEAK = 120  # (160 - n) * n^3 / 100 peaks here; decreasing afterwards
ERRATIC_TAIL_STEP = erratic_vanilla(100) - erratic_vanilla(99)  # 99->100 step

def erratic(n):
    if n <= ERRATIC_PEAK:
        return erratic_vanilla(n)
    return erratic_vanilla(ERRATIC_PEAK) + ERRATIC_TAIL_STEP * (n - ERRATIC_PEAK)


def table(f):
    # Vanilla anchors: entry 0 is 0 and entry 1 is 1 for every rate (Medium
    # Slow's formula is negative at 1, so Game Freak hardcoded these).
    return [0, 1] + [f(n) for n in range(2, MAX_LEVEL + 1)]


# Order must match enum GrowthRate; the trailing Medium Fast copies mirror the
# two unused vanilla growth-rate slots.
RATES = [
    ("Medium Fast", medium_fast),
    ("Erratic", erratic),
    ("Fluctuating", fluctuating),
    ("Medium Slow", medium_slow),
    ("Fast", fast),
    ("Slow", slow),
    ("Medium Fast copy 2 (unused vanilla slot)", medium_fast),
    ("Medium Fast copy 3 (unused vanilla slot)", medium_fast),
]

# Level 100 totals straight from the vanilla games; the generator refuses to
# emit anything that disagrees with them.
VANILLA_100 = {
    "Medium Fast": 1_000_000,
    "Erratic": 600_000,
    "Fluctuating": 1_640_000,
    "Medium Slow": 1_059_860,
    "Fast": 800_000,
    "Slow": 1_250_000,
}


def validate(tables):
    for name, vals in tables:
        base = name.split(" copy")[0]
        assert vals[100] == VANILLA_100[base], f"{name}: level 100 total {vals[100]} != vanilla"
        assert len(vals) == MAX_LEVEL + 1, f"{name}: {len(vals)} entries"
        for i in range(1, MAX_LEVEL):
            assert vals[i] < vals[i + 1], f"{name}: not monotonic at level {i + 1}"
        assert vals[MAX_LEVEL] < (1 << EXP_BITS), \
            f"{name}: {vals[MAX_LEVEL]} exceeds the {EXP_BITS}-bit experience field"


def main():
    tables = [(name, table(f)) for name, f in RATES]
    validate(tables)
    maxima = {n: v[MAX_LEVEL] for n, v in tables}
    if "--check" in sys.argv[1:]:
        print("OK:", ", ".join(f"{n.split(' copy')[0]}@255={v:,}" for n, v in maxima.items()))
        return

    lines = []
    lines.append("// Generated by tools/gen_exp_tables.py - do not hand-edit.")
    lines.append("// Levels 0..100 are the exact Gen 3 tables; levels 101+ continue each rate's")
    lines.append("// closed-form formula (Erratic: closed form through its peak at 120, then a")
    lines.append("// linear tail of its 99->100 step, since the formula is non-monotonic past")
    lines.append("// 120 and negative past 160). Values are plain literals so no compile-time")
    lines.append("// integer overflow can occur.")
    lines.append("const u32 gExperienceTables[][MAX_LEVEL + 1] =")
    lines.append("{")
    for name, vals in tables:
        lines.append(f"    {{ // {name}")
        for lvl, v in enumerate(vals):
            lines.append(f"        {v}, // {lvl}")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("// The experience value is stored in 24 + 2 bits in PokemonSubstruct0")
    lines.append("// (experience + experienceHi); make sure no total can overflow it.")
    for name, vals in tables:
        ident = "".join(w.capitalize() for w in name.split(" copy")[0].split())
        suffix = "Copy2" if "copy 2" in name else "Copy3" if "copy 3" in name else ""
        lines.append(f"STATIC_ASSERT({vals[MAX_LEVEL]} < (1 << {EXP_BITS}), ExpTable{ident}{suffix}Overflow);")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines);",
          "max total:", max(maxima.values()), f"(fits {EXP_BITS} bits)")


if __name__ == "__main__":
    main()
